version: "3.7"

services:
  database_gymapp:
    image: postgres
    container_name: database_gymapp
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gymapp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local